ASM=avra



all: hex

hex: $(TARGET).asm
	avra $(TARGET).asm --includepath ../..

flash: hex
	# TODO find the right programmer for my usb thingie. 
	avrdude -p m103  -c usbasp -u -U flash:w:$(TARGET).hex

clean:
	rm -rf *.cof
	rm -rf *.hex
	rm -rf *.obj
